# Generated by Django 6.0.4 on 2026-06-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histlpu',
            name='lpudt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прикрепления'),
        ),
    ]
